# Generated by Django 3.0.4 on 2021-04-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dizitracemvp03', '0002_retailer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retailer',
            new_name='Retailerd',
        ),
    ]
