# Generated by Django 3.0.4 on 2021-04-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizitracemvp03', '0003_auto_20210411_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailerdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_of_product', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=50, null=True)),
                ('current_owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order_no', models.CharField(blank=True, max_length=50, null=True)),
                ('handoff_timestamp', models.DateField(blank=True, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('product_category', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_disease', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Retailerd',
        ),
    ]
