# Generated by Django 3.0.4 on 2021-04-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dizitracemvp03', '0004_auto_20210411_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retailerdd',
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
    ]
