# Generated by Django 3.0.4 on 2021-04-30 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dizitracemvp03', '0005_auto_20210426_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='bulk_insert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=300)),
                ('manufacturer_name', models.CharField(default='', max_length=300)),
                ('product_group', models.CharField(default='', max_length=300)),
                ('prodcut_description', models.CharField(default='', max_length=300)),
                ('brand', models.CharField(default='', max_length=300)),
                ('ndc', models.CharField(default='', max_length=300)),
                ('manufacturing_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('product_expiry_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('gtin', models.CharField(default='', max_length=300)),
                ('licence_number', models.CharField(default='', max_length=300)),
                ('unit_of_measure_per_pack', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
