# Generated by Django 3.0.4 on 2021-05-01 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizitracemvp03', '0007_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='bulk_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=300)),
                ('manufacturer_name', models.CharField(default='', max_length=300)),
                ('product_group', models.CharField(default='', max_length=300)),
                ('prodcut_description', models.CharField(default='', max_length=300)),
                ('brand', models.CharField(default='', max_length=300)),
                ('ndc', models.CharField(default='', max_length=300)),
                ('manufacturing_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('product_expiry_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('gtin', models.CharField(default='', max_length=300)),
                ('licence_number', models.CharField(default='', max_length=300)),
                ('unit_of_measure_per_pack', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
