# Generated by Django 3.0.4 on 2021-05-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dizitracemvp03', '0008_bulk_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulk_upload',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='bulk_upload',
            name='gtin',
        ),
        migrations.RemoveField(
            model_name='bulk_upload',
            name='licence_number',
        ),
        migrations.RemoveField(
            model_name='bulk_upload',
            name='manufacturing_date',
        ),
        migrations.RemoveField(
            model_name='bulk_upload',
            name='ndc',
        ),
        migrations.RemoveField(
            model_name='bulk_upload',
            name='prodcut_description',
        ),
        migrations.RemoveField(
            model_name='bulk_upload',
            name='product_expiry_date',
        ),
        migrations.RemoveField(
            model_name='bulk_upload',
            name='unit_of_measure_per_pack',
        ),
    ]
