# Generated by Django 3.0.4 on 2021-05-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizitracemvp03', '0010_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='bulkdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('manufacturer_name', models.EmailField(blank=True, max_length=254)),
                ('product_group', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
