# Generated by Django 3.0.4 on 2021-05-01 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizitracemvp03', '0011_auto_20210501_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdata',
            name='brand',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='bulkdata',
            name='gtin',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='bulkdata',
            name='licence_number',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='bulkdata',
            name='manufacturing_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bulkdata',
            name='ndc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='bulkdata',
            name='prodcut_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='bulkdata',
            name='product_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bulkdata',
            name='unit_of_measure_per_pack',
            field=models.CharField(default='', max_length=300),
        ),
    ]
