from django.urls import path
from .import views

urlpatterns = [
path('dashboard/',views.dashboardview,name='dashboard'),
path('base_admin_dashboard/',views.base_admin_dashboardview,name='base_admin_dashboard'),
# path('base_operator_dashboard/',views.base_operator_dashboardview,name='base_operator_dashboard'),
# path('operator_dashboard/',views.dashboardoperatorview,name='operator_dashboard'),
# path('manager_dashboard/',views.dashboardmanagerview,name='manager_dashboard'),
# path('executive_dashboard/',views.dashboardexecutiveview,name='executive_dashboard'),
path('popup/',views.popupview,name='popup'),
path('operatordashboard/',views.operatordashboard,name='operatordashboard'),
path('user_profile/',views.user_profileview,name='user_profile'),
path('add_user_register/',views.add_userview,name='add_user'),
path('add_user/',views.add_user_emailview,name='add_user'),
path('registerform_1/',views.registerform_idview,name='registerform_1'),
path('accounts/',views.accountsview,name='accounts'),
path('roles/',views.rolesview,name='roles'),
path('permissions/',views.permissionsview,name='permissions'),
path('licence/',views.licenceview,name='licence'),
path('manufacturer_order_details_edit/<int:id>',views.manufacturer_order_details_edit_view,name='manufacturer_order_details_edit'),
path('manufacturer_order_details/',views.manufacturer_order_details_view,name='manufacturer_order_details'),
# path('update/<int:id>',views.manufacturer_order_update,name='update'),
path('manufacturer_order_update/',views.manufacturer_order_update,name='manufacturer_order_update'),

path('logistics_order_details_edit/<int:id>',views.logistics_order_details_edit_view,name='logistics_order_details_edit'),
path('logistics_order_details/',views.logistics_order_details_view,name='logistics_order_details'),
path('logistics_order_update/',views.logistics_order_update,name='logistics_order_update'),

path('retailer_order_details_edit/<int:id>',views.retailer_order_details_edit_view,name='retailer_order_details_edit'),
path('retailer_order_details/',views.retailer_order_details_view,name='retailer_order_details'),
path('retailer_order_update/',views.retailer_order_update,name='retailer_order_update'),

path('show',views.show,name='show'),
path('search/',views.search,name='search'),
path('trace',views.trace,name='trace'),
path('transactionform',views.transactionformview,name='transactionform'),
path('verification/',views.verification,name='verification'),
path('trace_identification/',views.trace_identification,name='trace_identification'),
path('retailer_identify',views.retailer_identify,name='retailer_identify'),
path('retailer_identification/',views.retailer_identification,name='retailer_identification'),
path('distributor_identify',views.distributor_identify,name='distributor_identify'),
path('distributor_identification/',views.distributor_identification,name='distributor_identification'),
path('lsp_identify',views.lsp_identify,name='lsp_identify'),
path('lsp_identification/',views.lsp_identification,name='lsp_identification'),
path('base/',views.base_view,name='base'),
path('error/',views.error_view,name='error'),
path('error1/',views.error1_view,name='error1'),
path('map/',views.maps_view,name='map'),
path('home/',views.homeview,name='home'),
# path('registerform1/',views.registerform1_view,name='registerform1'),
path('details/',views.detailsview,name='details'),
path('',views.loginview,name='login'),
path('logout',views.logoutview,name='logout'),
path('Reset-password/',views.resetpasswordview,name='Reset-password'),
path('Forgot-password/',views.forgotpasswordview,name='forgot-password'),
path('Register-form-1/',views.registerform1view,name='Register-form-1'),
path('register/',views.registerview,name='register'),
# path('bulk_insert/',views.simple_upload,name='bulk_insert'),
path('Registration-form-2/',views.registerform2view,name='Registration-form-2'),
path('Reset-password/',views.reset_password,name='Reset-password'),
]
